# coding: utf-8

"""
    ClickSend v3 API

     This is an official SDK for [ClickSend](https://clicksend.com)  Below you will find a current list of the available methods for clicksend.  *NOTE: You will need to create a free account to use the API. You can register [here](https://dashboard.clicksend.com/#/signup/step1/)..*   # noqa: E501

    OpenAPI spec version: 3.1
    Contact: support@clicksend.com
    Generated by: https://github.com/clicksend-api/clicksend-codegen.git
"""


from __future__ import absolute_import

import unittest

import clicksend_client
from clicksend_client.api.mms_api import MMSApi  # noqa: E501
from clicksend_client.rest import ApiException


class TestMMSApi(unittest.TestCase):
    """MMSApi unit test stubs"""

    def setUp(self):
        self.api = clicksend_client.api.mms_api.MMSApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_mms_history_export_get(self):
        """Test case for mms_history_export_get

        Export all mms history  # noqa: E501
        """
        pass

    def test_mms_history_get(self):
        """Test case for mms_history_get

        Get all mms history  # noqa: E501
        """
        pass

    def test_mms_price_post(self):
        """Test case for mms_price_post

        Get Price for MMS sent  # noqa: E501
        """
        pass

    def test_mms_receipts_get(self):
        """Test case for mms_receipts_get

        Get all delivery receipts  # noqa: E501
        """
        pass

    def test_mms_receipts_read_put(self):
        """Test case for mms_receipts_read_put

        Mark delivery receipts as read  # noqa: E501
        """
        pass

    def test_mms_send_post(self):
        """Test case for mms_send_post

        Send MMS  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
