# coding: utf-8

"""
    ClickSend v3 API

     This is an official SDK for [ClickSend](https://clicksend.com)  Below you will find a current list of the available methods for clicksend.  *NOTE: You will need to create a free account to use the API. You can register [here](https://dashboard.clicksend.com/#/signup/step1/)..*   # noqa: E501

    OpenAPI spec version: 3.1
    Contact: support@clicksend.com
    Generated by: https://github.com/clicksend-api/clicksend-codegen.git
"""


from __future__ import absolute_import

import unittest

import clicksend_client
from clicksend_client.api.transactional_email_api import TransactionalEmailApi  # noqa: E501
from clicksend_client.rest import ApiException


class TestTransactionalEmailApi(unittest.TestCase):
    """TransactionalEmailApi unit test stubs"""

    def setUp(self):
        self.api = clicksend_client.api.transactional_email_api.TransactionalEmailApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_email_history_export_get(self):
        """Test case for email_history_export_get

        Export all Transactional Email history  # noqa: E501
        """
        pass

    def test_email_history_get(self):
        """Test case for email_history_get

        Get all transactional email history  # noqa: E501
        """
        pass

    def test_email_price_post(self):
        """Test case for email_price_post

        Get transactional email price  # noqa: E501
        """
        pass

    def test_email_send_post(self):
        """Test case for email_send_post

        Send transactional email  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
