# coding: utf-8

"""
    ClickSend v3 API

     This is an official SDK for [ClickSend](https://clicksend.com)  Below you will find a current list of the available methods for clicksend.  *NOTE: You will need to create a free account to use the API. You can register [here](https://dashboard.clicksend.com/#/signup/step1/)..*   # noqa: E501

    OpenAPI spec version: 3.1
    Contact: support@clicksend.com
    Generated by: https://github.com/clicksend-api/clicksend-codegen.git
"""


from __future__ import absolute_import

import unittest

import clicksend_client
from clicksend_client.api.contact_list_api import ContactListApi  # noqa: E501
from clicksend_client.rest import ApiException


class TestContactListApi(unittest.TestCase):
    """ContactListApi unit test stubs"""

    def setUp(self):
        self.api = clicksend_client.api.contact_list_api.ContactListApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_lists_by_list_id_delete(self):
        """Test case for lists_by_list_id_delete

        ListsByListIdDelete  # noqa: E501
        """
        pass

    def test_lists_by_list_id_get(self):
        """Test case for lists_by_list_id_get

        Get specific contact list  # noqa: E501
        """
        pass

    def test_lists_by_list_id_put(self):
        """Test case for lists_by_list_id_put

        Update specific contact list  # noqa: E501
        """
        pass

    def test_lists_get(self):
        """Test case for lists_get

        Get all contact lists  # noqa: E501
        """
        pass

    def test_lists_import_by_list_id_post(self):
        """Test case for lists_import_by_list_id_post

        Import contacts to list  # noqa: E501
        """
        pass

    def test_lists_post(self):
        """Test case for lists_post

        Create new contact list  # noqa: E501
        """
        pass

    def test_lists_remove_duplicates_by_list_id_put(self):
        """Test case for lists_remove_duplicates_by_list_id_put

        Remove duplicate contacts  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
