# coding: utf-8

"""
    ClickSend v3 REST API

     This is the official [ClickSend](https://clicksend.com) SDK.  *You'll need to create a free account to use the API. You can register [here](https://www.clicksend.com/signup).*  You can use our API documentation along with the SDK. Our API docs can be found [here](https://developers.clicksend.com).   # noqa: E501

    OpenAPI spec version: 3.1.0
    Contact: support@clicksend.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.post_direct_mail_api import PostDirectMailApi  # noqa: E501
from swagger_client.rest import ApiException


class TestPostDirectMailApi(unittest.TestCase):
    """PostDirectMailApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.post_direct_mail_api.PostDirectMailApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_post_direct_mail_campaigns_get(self):
        """Test case for post_direct_mail_campaigns_get

        Get direct mail campaigns  # noqa: E501
        """
        pass

    def test_post_direct_mail_campaigns_price_post(self):
        """Test case for post_direct_mail_campaigns_price_post

        Calculate direct mail campaign price  # noqa: E501
        """
        pass

    def test_post_direct_mail_campaigns_send_post(self):
        """Test case for post_direct_mail_campaigns_send_post

        Send direct mail campaign  # noqa: E501
        """
        pass

    def test_post_direct_mail_locations_search_by_country_get(self):
        """Test case for post_direct_mail_locations_search_by_country_get

        Search for a location  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
