# coding: utf-8

"""
    ClickSend v3 REST API

     This is the official [ClickSend](https://clicksend.com) SDK.  *You'll need to create a free account to use the API. You can register [here](https://www.clicksend.com/signup).*  You can use our API documentation along with the SDK. Our API docs can be found [here](https://developers.clicksend.com).   # noqa: E501

    OpenAPI spec version: 3.1.0
    Contact: support@clicksend.com
    Generated by: https://github.com/clicksend-api/clicksend-codegen.git
"""


from __future__ import absolute_import

import unittest

import clicksend_client
from clicksend_client.api.fax_api import FaxApi  # noqa: E501
from clicksend_client.rest import ApiException


class TestFaxApi(unittest.TestCase):
    """FaxApi unit test stubs"""

    def setUp(self):
        self.api = clicksend_client.api.fax_api.FaxApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_fax_history_get(self):
        """Test case for fax_history_get

        Get a list of Fax History.  # noqa: E501
        """
        pass

    def test_fax_price_post(self):
        """Test case for fax_price_post

        Calculate Total Price for Fax Messages sent  # noqa: E501
        """
        pass

    def test_fax_receipts_by_message_id_get(self):
        """Test case for fax_receipts_by_message_id_get

        Get a single fax receipt based on message id.  # noqa: E501
        """
        pass

    def test_fax_receipts_get(self):
        """Test case for fax_receipts_get

        Get List of Fax Receipts  # noqa: E501
        """
        pass

    def test_fax_send_post(self):
        """Test case for fax_send_post

        Send a fax using supplied supported file-types.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
