# coding: utf-8

"""
    ClickSend v3 API

     This is an official SDK for [ClickSend](https://clicksend.com)  Below you will find a current list of the available methods for clicksend.  *NOTE: You will need to create a free account to use the API. You can register [here](https://dashboard.clicksend.com/#/signup/step1/)..*   # noqa: E501

    OpenAPI spec version: 3.1
    Contact: support@clicksend.com
    Generated by: https://github.com/clicksend-api/clicksend-codegen.git
"""


from __future__ import absolute_import

import unittest

import clicksend_client
from clicksend_client.api.voice_delivery_receipt_rules_api import VoiceDeliveryReceiptRulesApi  # noqa: E501
from clicksend_client.rest import ApiException


class TestVoiceDeliveryReceiptRulesApi(unittest.TestCase):
    """VoiceDeliveryReceiptRulesApi unit test stubs"""

    def setUp(self):
        self.api = clicksend_client.api.voice_delivery_receipt_rules_api.VoiceDeliveryReceiptRulesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_voice_delivery_receipt_automation_delete(self):
        """Test case for voice_delivery_receipt_automation_delete

        Delete voice delivery receipt automation  # noqa: E501
        """
        pass

    def test_voice_delivery_receipt_automation_get(self):
        """Test case for voice_delivery_receipt_automation_get

        Get specific voice delivery receipt automation  # noqa: E501
        """
        pass

    def test_voice_delivery_receipt_automation_post(self):
        """Test case for voice_delivery_receipt_automation_post

        Create voice delivery receipt automations  # noqa: E501
        """
        pass

    def test_voice_delivery_receipt_automation_put(self):
        """Test case for voice_delivery_receipt_automation_put

        Update voice delivery receipt automation  # noqa: E501
        """
        pass

    def test_voice_delivery_receipt_automations_get(self):
        """Test case for voice_delivery_receipt_automations_get

        Get all voice delivery receipt automations  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
