# coding: utf-8

"""
    ClickSend v3 REST API

     This is the official [ClickSend](https://clicksend.com) SDK.  *You'll need to create a free account to use the API. You can register [here](https://www.clicksend.com/signup).*  You can use our API documentation along with the SDK. Our API docs can be found [here](https://developers.clicksend.com).   # noqa: E501

    OpenAPI spec version: 3.1.0
    Contact: support@clicksend.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from ClickSend.Client.Api.voice_api import VoiceApi  # noqa: E501
from swagger_client.rest import ApiException


class TestVoiceApi(unittest.TestCase):
    """VoiceApi unit test stubs"""

    def setUp(self):
        self.api = ClickSend.Client.Api.voice_api.VoiceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_voice_cancel_all_put(self):
        """Test case for voice_cancel_all_put

        Update all voice messages as cancelled  # noqa: E501
        """
        pass

    def test_voice_cancel_by_message_id_put(self):
        """Test case for voice_cancel_by_message_id_put

        Update voice message status as cancelled  # noqa: E501
        """
        pass

    def test_voice_history_export_get(self):
        """Test case for voice_history_export_get

        Export voice history  # noqa: E501
        """
        pass

    def test_voice_history_get(self):
        """Test case for voice_history_get

        Get all voice history  # noqa: E501
        """
        pass

    def test_voice_lang_get(self):
        """Test case for voice_lang_get

        Get all voice languages  # noqa: E501
        """
        pass

    def test_voice_price_post(self):
        """Test case for voice_price_post

        Calculate voice price  # noqa: E501
        """
        pass

    def test_voice_receipts_get(self):
        """Test case for voice_receipts_get

        Get all voice receipts  # noqa: E501
        """
        pass

    def test_voice_send_post(self):
        """Test case for voice_send_post

        Send voice message(s)  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
