# coding: utf-8

"""
    ClickSend v3 REST API

     This is the official [ClickSend](https://clicksend.com) SDK.  *You'll need to create a free account to use the API. You can register [here](https://www.clicksend.com/signup).*  You can use our API documentation along with the SDK. Our API docs can be found [here](https://developers.clicksend.com).   # noqa: E501

    OpenAPI spec version: 3.1.0
    Contact: support@clicksend.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from ClickSend.Client.Api.transactional_email_api import TransactionalEmailApi  # noqa: E501
from swagger_client.rest import ApiException


class TestTransactionalEmailApi(unittest.TestCase):
    """TransactionalEmailApi unit test stubs"""

    def setUp(self):
        self.api = ClickSend.Client.Api.transactional_email_api.TransactionalEmailApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_email_history_export_get(self):
        """Test case for email_history_export_get

        Export all Transactional Email history  # noqa: E501
        """
        pass

    def test_email_history_get(self):
        """Test case for email_history_get

        Get all transactional email history  # noqa: E501
        """
        pass

    def test_email_price_post(self):
        """Test case for email_price_post

        Get transactional email price  # noqa: E501
        """
        pass

    def test_email_send_post(self):
        """Test case for email_send_post

        Send transactional email  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
