# coding: utf-8

"""
    ClickSend v3 REST API

     This is the official [ClickSend](https://clicksend.com) SDK.  *You'll need to create a free account to use the API. You can register [here](https://www.clicksend.com/signup).*  You can use our API documentation along with the SDK. Our API docs can be found [here](https://developers.clicksend.com).   # noqa: E501

    OpenAPI spec version: 3.1.0
    Contact: support@clicksend.com
    Generated by: https://github.com/clicksend-api/clicksend-codegen.git
"""


from __future__ import absolute_import

import unittest

import clicksend_client
from clicksend_client.api.account_recharge_api import AccountRechargeApi  # noqa: E501
from clicksend_client.rest import ApiException


class TestAccountRechargeApi(unittest.TestCase):
    """AccountRechargeApi unit test stubs"""

    def setUp(self):
        self.api = clicksend_client.api.account_recharge_api.AccountRechargeApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_recharge_credit_card_get(self):
        """Test case for recharge_credit_card_get

        Get Credit Card info  # noqa: E501
        """
        pass

    def test_recharge_credit_card_put(self):
        """Test case for recharge_credit_card_put

        Update credit card info  # noqa: E501
        """
        pass

    def test_recharge_packages_get(self):
        """Test case for recharge_packages_get

        Get list of all packages  # noqa: E501
        """
        pass

    def test_recharge_purchase_by_package_id_put(self):
        """Test case for recharge_purchase_by_package_id_put

        Purchase a package  # noqa: E501
        """
        pass

    def test_recharge_transactions_by_transaction_id_get(self):
        """Test case for recharge_transactions_by_transaction_id_get

        Get specific Transaction  # noqa: E501
        """
        pass

    def test_recharge_transactions_get(self):
        """Test case for recharge_transactions_get

        Purchase a package  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
