# coding: utf-8

"""
    ClickSend v3 REST API

     This is the official [ClickSend](https://clicksend.com) SDK.  *You'll need to create a free account to use the API. You can register [here](https://www.clicksend.com/signup).*  You can use our API documentation along with the SDK. Our API docs can be found [here](https://developers.clicksend.com).   # noqa: E501

    OpenAPI spec version: 3.1.0
    Contact: support@clicksend.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from clicksend.api.subaccount_api import SubaccountApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSubaccountApi(unittest.TestCase):
    """SubaccountApi unit test stubs"""

    def setUp(self):
        self.api = clicksend.api.subaccount_api.SubaccountApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_subaccounts_by_subaccount_id_delete(self):
        """Test case for subaccounts_by_subaccount_id_delete

        Delete a subaccount  # noqa: E501
        """
        pass

    def test_subaccounts_by_subaccount_id_get(self):
        """Test case for subaccounts_by_subaccount_id_get

        Get specific subaccount  # noqa: E501
        """
        pass

    def test_subaccounts_by_subaccount_id_put(self):
        """Test case for subaccounts_by_subaccount_id_put

        Update subaccount  # noqa: E501
        """
        pass

    def test_subaccounts_get(self):
        """Test case for subaccounts_get

        Get all subaccounts  # noqa: E501
        """
        pass

    def test_subaccounts_post(self):
        """Test case for subaccounts_post

        Create new subaccount  # noqa: E501
        """
        pass

    def test_subaccounts_regen_api_key_by_subaccount_id_put(self):
        """Test case for subaccounts_regen_api_key_by_subaccount_id_put

        Regenerate an API Key  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
