# coding: utf-8

"""
    ClickSend v3 API

     This is an official SDK for [ClickSend](https://clicksend.com)  Below you will find a current list of the available methods for clicksend.  *NOTE: You will need to create a free account to use the API. You can register [here](https://dashboard.clicksend.com/#/signup/step1/)..*   # noqa: E501

    OpenAPI spec version: 3.1
    Contact: support@clicksend.com
    Generated by: https://github.com/clicksend-api/clicksend-codegen.git
"""


from __future__ import absolute_import

import unittest

import clicksend_client
from clicksend_client.models.upload_file import UploadFile  # noqa: E501
from clicksend_client.rest import ApiException


class TestUploadFile(unittest.TestCase):
    """UploadFile unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUploadFile(self):
        """Test UploadFile"""
        # FIXME: construct object with mandatory attributes with example values
        # model = clicksend_client.models.upload_file.UploadFile()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
