# coding: utf-8

"""
    ClickSend v3 REST API

     This is the official [ClickSend](https://clicksend.com) SDK.  *You'll need to create a free account to use the API. You can register [here](https://www.clicksend.com/signup).*  You can use our API documentation along with the SDK. Our API docs can be found [here](https://developers.clicksend.com).   # noqa: E501

    OpenAPI spec version: 3.1.0
    Contact: support@clicksend.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.email_delivery_receipt_rules_api import EmailDeliveryReceiptRulesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestEmailDeliveryReceiptRulesApi(unittest.TestCase):
    """EmailDeliveryReceiptRulesApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.email_delivery_receipt_rules_api.EmailDeliveryReceiptRulesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_email_delivery_receipt_automation_delete(self):
        """Test case for email_delivery_receipt_automation_delete

        Delete email delivery receipt automation  # noqa: E501
        """
        pass

    def test_email_delivery_receipt_automation_get(self):
        """Test case for email_delivery_receipt_automation_get

        Get specific email delivery receipt automation  # noqa: E501
        """
        pass

    def test_email_delivery_receipt_automation_post(self):
        """Test case for email_delivery_receipt_automation_post

        Create email delivery receipt automations  # noqa: E501
        """
        pass

    def test_email_delivery_receipt_automation_put(self):
        """Test case for email_delivery_receipt_automation_put

        Update email delivery receipt automation  # noqa: E501
        """
        pass

    def test_email_delivery_receipt_automations_get(self):
        """Test case for email_delivery_receipt_automations_get

        Get all email delivery receipt automations  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
