# coding: utf-8

"""
    ClickSend v3 API

     This is an official SDK for [ClickSend](https://clicksend.com)  Below you will find a current list of the available methods for clicksend.  *NOTE: You will need to create a free account to use the API. You can register [here](https://dashboard.clicksend.com/#/signup/step1/)..*   # noqa: E501

    OpenAPI spec version: 3.1
    Contact: support@clicksend.com
    Generated by: https://github.com/clicksend-api/clicksend-codegen.git
"""


from __future__ import absolute_import

import unittest

import clicksend_client
from clicksend_client.api.subaccount_api import SubaccountApi  # noqa: E501
from clicksend_client.rest import ApiException


class TestSubaccountApi(unittest.TestCase):
    """SubaccountApi unit test stubs"""

    def setUp(self):
        self.api = clicksend_client.api.subaccount_api.SubaccountApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_subaccounts_by_subaccount_id_delete(self):
        """Test case for subaccounts_by_subaccount_id_delete

        Delete a subaccount  # noqa: E501
        """
        pass

    def test_subaccounts_by_subaccount_id_get(self):
        """Test case for subaccounts_by_subaccount_id_get

        Get specific subaccount  # noqa: E501
        """
        pass

    def test_subaccounts_by_subaccount_id_put(self):
        """Test case for subaccounts_by_subaccount_id_put

        Update subaccount  # noqa: E501
        """
        pass

    def test_subaccounts_get(self):
        """Test case for subaccounts_get

        Get all subaccounts  # noqa: E501
        """
        pass

    def test_subaccounts_post(self):
        """Test case for subaccounts_post

        Create new subaccount  # noqa: E501
        """
        pass

    def test_subaccounts_regen_api_key_by_subaccount_id_put(self):
        """Test case for subaccounts_regen_api_key_by_subaccount_id_put

        Regenerate an API Key  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
