# coding: utf-8

"""
    ClickSend v3 REST API

     This is the official [ClickSend](https://clicksend.com) SDK.  *You'll need to create a free account to use the API. You can register [here](https://www.clicksend.com/signup).*  You can use our API documentation along with the SDK. Our API docs can be found [here](https://developers.clicksend.com).   # noqa: E501

    OpenAPI spec version: 3.1.0
    Contact: support@clicksend.com
    Generated by: https://github.com/clicksend-api/clicksend-codegen.git
"""


from __future__ import absolute_import

import unittest

import clicksend_client
from clicksend_client.api.sms_campaign_api import SmsCampaignApi  # noqa: E501
from clicksend_client.rest import ApiException


class TestSmsCampaignApi(unittest.TestCase):
    """SmsCampaignApi unit test stubs"""

    def setUp(self):
        self.api = clicksend_client.api.sms_campaign_api.SmsCampaignApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_sms_campaign_by_sms_campaign_id_get(self):
        """Test case for sms_campaign_by_sms_campaign_id_get

        Get specific sms campaign  # noqa: E501
        """
        pass

    def test_sms_campaigns_by_sms_campaign_id_put(self):
        """Test case for sms_campaigns_by_sms_campaign_id_put

        Update sms campaign  # noqa: E501
        """
        pass

    def test_sms_campaigns_cancel_by_sms_campaign_id_put(self):
        """Test case for sms_campaigns_cancel_by_sms_campaign_id_put

        Cancel sms campaign  # noqa: E501
        """
        pass

    def test_sms_campaigns_get(self):
        """Test case for sms_campaigns_get

        Get list of sms campaigns  # noqa: E501
        """
        pass

    def test_sms_campaigns_price_post(self):
        """Test case for sms_campaigns_price_post

        Calculate price for sms campaign  # noqa: E501
        """
        pass

    def test_sms_campaigns_send_post(self):
        """Test case for sms_campaigns_send_post

        Create sms campaign  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
