# coding: utf-8

"""
    ClickSend v3 API

     This is an official SDK for [ClickSend](https://clicksend.com)  Below you will find a current list of the available methods for clicksend.  *NOTE: You will need to create a free account to use the API. You can register [here](https://dashboard.clicksend.com/#/signup/step1/)..*   # noqa: E501

    OpenAPI spec version: 3.1
    Contact: support@clicksend.com
    Generated by: https://github.com/clicksend-api/clicksend-codegen.git
"""


from __future__ import absolute_import

import unittest

import clicksend_client
from clicksend_client.api.mms_campaign_api import MmsCampaignApi  # noqa: E501
from clicksend_client.rest import ApiException


class TestMmsCampaignApi(unittest.TestCase):
    """MmsCampaignApi unit test stubs"""

    def setUp(self):
        self.api = clicksend_client.api.mms_campaign_api.MmsCampaignApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_mms_campaign_by_mms_campaign_id_get(self):
        """Test case for mms_campaign_by_mms_campaign_id_get

        Get specific mms campaign  # noqa: E501
        """
        pass

    def test_mms_campaigns_by_mms_campaign_id_put(self):
        """Test case for mms_campaigns_by_mms_campaign_id_put

        Update mms campaign  # noqa: E501
        """
        pass

    def test_mms_campaigns_cancel_by_mms_campaign_id_put(self):
        """Test case for mms_campaigns_cancel_by_mms_campaign_id_put

        Cancel mms campaign  # noqa: E501
        """
        pass

    def test_mms_campaigns_get(self):
        """Test case for mms_campaigns_get

        Get list of mms campaigns  # noqa: E501
        """
        pass

    def test_mms_campaigns_price_post(self):
        """Test case for mms_campaigns_price_post

        Calculate price for mms campaign  # noqa: E501
        """
        pass

    def test_mms_campaigns_send_post(self):
        """Test case for mms_campaigns_send_post

        Create mms campaign  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
