# coding: utf-8

"""
    ClickSend v3 API

     This is an official SDK for [ClickSend](https://clicksend.com)  Below you will find a current list of the available methods for clicksend.  *NOTE: You will need to create a free account to use the API. You can register [here](https://dashboard.clicksend.com/#/signup/step1/)..*   # noqa: E501

    OpenAPI spec version: 3.1
    Contact: support@clicksend.com
    Generated by: https://github.com/clicksend-api/clicksend-codegen.git
"""


from __future__ import absolute_import

import unittest

import clicksend_client
from clicksend_client.api.timezones_api import TimezonesApi  # noqa: E501
from clicksend_client.rest import ApiException


class TestTimezonesApi(unittest.TestCase):
    """TimezonesApi unit test stubs"""

    def setUp(self):
        self.api = clicksend_client.api.timezones_api.TimezonesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_timezones_get(self):
        """Test case for timezones_get

        Get supported list of timezones.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
