# coding: utf-8

"""
    ClickSend v3 REST API

     This is the official [ClickSend](https://clicksend.com) SDK.  *You'll need to create a free account to use the API. You can register [here](https://www.clicksend.com/signup).*  You can use our API documentation along with the SDK. Our API docs can be found [here](https://developers.clicksend.com).   # noqa: E501

    OpenAPI spec version: 3.1.0
    Contact: support@clicksend.com
    Generated by: https://github.com/clicksend-api/clicksend-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ContactListImport(object):
    """NOTE: This class is auto generated by the clicksend code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      clicksend_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    clicksend_types = {
        'file_url': 'str',
        'field_order': 'list[str]'
    }

    attribute_map = {
        'file_url': 'file_url',
        'field_order': 'field_order'
    }

    discriminator_value_class_map = {
        
    }

    def __init__(self, file_url=None, field_order=None):  # noqa: E501
        """ContactListImport - a model defined in Swagger"""  # noqa: E501

        self._file_url = None
        self._field_order = None
        self.discriminator = 'classType'

        self.file_url = file_url
        self.field_order = field_order

    @property
    def file_url(self):
        """Gets the file_url of this ContactListImport.  # noqa: E501

        URL of file to process  # noqa: E501

        :return: The file_url of this ContactListImport.  # noqa: E501
        :rtype: str
        """
        return self._file_url

    @file_url.setter
    def file_url(self, file_url):
        """Sets the file_url of this ContactListImport.

        URL of file to process  # noqa: E501

        :param file_url: The file_url of this ContactListImport.  # noqa: E501
        :type: str
        """
        if file_url is None:
            raise ValueError("Invalid value for `file_url`, must not be `None`")  # noqa: E501

        self._file_url = file_url

    @property
    def field_order(self):
        """Gets the field_order of this ContactListImport.  # noqa: E501

        Order of fields in file  # noqa: E501

        :return: The field_order of this ContactListImport.  # noqa: E501
        :rtype: list[str]
        """
        return self._field_order

    @field_order.setter
    def field_order(self, field_order):
        """Sets the field_order of this ContactListImport.

        Order of fields in file  # noqa: E501

        :param field_order: The field_order of this ContactListImport.  # noqa: E501
        :type: list[str]
        """
        if field_order is None:
            raise ValueError("Invalid value for `field_order`, must not be `None`")  # noqa: E501

        self._field_order = field_order

    def get_real_child_model(self, data):
        """Returns the real base class specified by the discriminator"""
        discriminator_value = data[self.discriminator].lower()
        return self.discriminator_value_class_map.get(discriminator_value)

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.clicksend_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ContactListImport, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ContactListImport):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
